# Site settings
title: "Martin Smith "
email: martin@mbs3.org
description: "DevOps, Travel, and Photography" # short
baseurl: ""
url: "http://martinb3.io/"
title_description: "DevOps, Travel, and Photography" # long
title_image: "http://www.gravatar.com/avatar/9ad2a5355d8cfa842e24b7a4322b2535?s=500&d=mm"
google_analytics: "UA-67814966-1"
disqus_account: martinb3
github_repository: https://github.com/martinb3/martinb3.github.io
addthis_id: ra-55ff62f22cee2dd5
post_limit: 5

# Social usernames/URLs
twitter_username: martinb3
github_username: martinb3
linkedin_link: https://www.linkedin.com/in/martinbsmith
google_plus_link: https://plus.google.com/+MartinSmith3/
stackoverflow_link: http://stackoverflow.com/users/70665/martin

# Footer
footer_left: "Content with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/martinb3\">Martin Smith</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/martinb3/martinb3.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
